import { Inter } from "next/font/google";
import './globals.css';
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-white`}>
        <Sidebar/>
        <div className="flex-1 p-4 bg-gray-100">
          {children}
        </div>
      </body>
    </html>
  );
}