import { Poppins } from 'next/font/google';
import './globals.css';
import Sidebar from "./components/Sidebar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex bg-white`}>
        <Sidebar/>
        <div className="flex-1 bg-gray-100">
          {children}
        </div>
      </body>
    </html>
  );
}